baseURL = "https://stefanolazzarato.github.io"
languageCode = "en-us"
title = "iNTRINSeCO"
theme = "beautifulhugo"

#defaultContentLanguage = "it"

metaDataFormat = "yaml"

[params]
  subtitle = "Think, plan, create"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  commit = false
  rss = true
  comments = false
  readingTime = true
  useHLJS = true

[author]
  name = "Stefano Lazzarato"
  website = "http://www.intrinseco.it"
  github = "stefanolazzarato"

[[menu.main]]
  name = "Blog"
  url = "/post"
  weight = 1

